# Initialization

Checking the version of Python installed. The next steps will be to:

*   import libraries
*   determine functions/classes (if needed)
*   create list of URLs.

So let's begin!

In [37]:
!python --version
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv

Python 3.12.12

We will save our datasets in the folder `./datasets`.

In [38]:
!rm -rf ./datasets
!mkdir ./datasets

Let's create a **list** where we will insert direct URLs for downloading csv files from `opendata.az`

In [39]:
### URLs can be inserted directly for the installation ###

### ToC

# 0 # NO DATA ON THE 0-th INDEX!
# 1 # Nəqliyyat sektorunda sərnişin daşınmasından əldə olunan gəlir ('https://opendata.az/@dsk/revenue-from-passenger-transportation-in-the-transportation-sector')
# 2 # Nəqliyyat sektorunda əlaqə növləri üzrə sərnişin daşınması, əvvəlki ilə nisbətən. ('https://opendata.az/@dsk/passenger-transportation-by-type-of-connection')
# 3 # Nəqliyyat sektorunda əlaqə növləri üzrə sərnişin daşınması, min sərnişin. ('https://opendata.az/@dsk/neqliyyat-sektorunda-elaqe-novleri-uzre-sernisin-dasinmasi-statistikasi')
# 4 # Nəqliyyat üzrə əsas makro göstəricilər ('https://opendata.az/@dsk/key-macro-indicators-for-transport')
# 5 # Nəqliyyat sektorunda 1 sərnişinin orta daşınma məsafəsi ('https://opendata.az/@dsk/average-transportation-distance-of-1-passenger-in-the-transport-sector/r/c488a8eb-bfe2-42ea-8a31-894e38492345')
# 6 # Boru kəməri nəqliyyatı üzrə əsas göstəricilər (natura ifadəsində) ('https://opendata.az/@dsk/boru-kemeri-neqliyyati-ile-bagli-statistik-gostericiler/r/d687598e-1c24-4621-8818-e5dd4a059412')

opendataurls = [None, 'https://admin.opendata.az/dataset/1cb0a662-8737-45c2-a3f8-c8fa21888a1a/resource/d51060b9-27cf-4dab-b2b2-4397b33371af/download/nqliyyat-sektorunda-srniin-danmasndan-ld-olunan-glir-min-manat-dt_bj_029.csv',
                'https://admin.opendata.az/dataset/3bfc0e38-0d09-4b51-a76e-6f12da9f5836/resource/307d26a9-fd7c-48e1-bb80-f3f19b809555/download/nqliyyat-sektorunda-laq-novlri-uzr-srniin-danmas-vvlki-il-nisbtn-dt_bj_005.csv',
                'https://admin.opendata.az/dataset/467cbf09-b828-47f7-acb1-befdba793435/resource/059d5f88-9b3b-42f5-ab08-b2b4525ed687/download/nqliyyat-sektorunda-laq-novlri-uzr-srniin-danmas-min-srniin-dt_bj_021.csv',
                'https://admin.opendata.az/dataset/2bf54269-fa55-4b9a-859b-2bd06c74f3d6/resource/1fe4226b-f616-4c95-8aa7-f7f62b9eb404/download/nqliyyat-uzr-sas-makro-gostricilr-dt_bj_002.csv',
                'https://admin.opendata.az/dataset/f3d36c3a-8bdc-4ceb-9bd5-2c73d2db2d8d/resource/c488a8eb-bfe2-42ea-8a31-894e38492345/download/nqliyyat-sektorunda-1-srniinin-orta-danma-msafsi-dt_bj_050.csv',
                'https://admin.opendata.az/dataset/4b62b286-efa5-455f-8b04-dadbf5ae2c23/resource/d687598e-1c24-4621-8818-e5dd4a059412/download/boru-kmri-nqliyyat-uzr-sas-gostricilr-natura-ifadsind-dt_bj_051.csv',
                ]

Creating 3 functions as:

1.   **downloadf** -> Download spesific dataset from the list `opendataurls` by their defined index.
2.   **loadf** -> it will be used to read csv files, converting them into pandas format. We will use `csv.sniffer` to determine delimiter.
3.   **sniffer** -> that will be used by `loadf` function

In [40]:
def loadf(index, bytes_to_sniff=4096, encoding='utf-8'):
  path = f'./datasets/data{index}.csv'
  return pd.read_csv(path, sep=sniffer(path, bytes_to_sniff, encoding))

def sniffer(file_path, bytes_to_sniff=4096, encoding='utf-8'):
    with open(file_path, 'r', newline='', encoding=encoding) as file:
        return csv.Sniffer().sniff(file.read(bytes_to_sniff)).delimiter

def downloadf(index):
    !wget -q --show-progress "{opendataurls[index]}" -O "./datasets/data{index}.csv"

Use the below to automatically download and load all the datasets defined in `opendataurls`

```python
for index in range(1, len(opendataurls)):
  downloadf(index)
  globals()[f'df{index}'] = loadf(index)
```

# `df1` preprocessing

This data preprocessed on:
*   `Year` replaced as index
*   `Columns translated to English
*    Unnecessary columns dropped
*    `Year` converted to `DateTime` format.
*    `Year` sorted

In [41]:
# In just a few words, we will download, determine seperator, and load csv into dataframe!

downloadf(1)
df1 = loadf(1)
df1.head()

./datasets/data1.cs 100%[===================>]   2.59K  --.-KB/s    in 0s

,Year,Unnamed: 1,Cəmi (min manat),Dəmir yolu (min manat),Dəniz (min manat),Hava (min manat),Avtomobil (min manat),Avtobus (min manat),Taksi (min manat),Metro (min manat),Tramvay (min manat),Trolleybus (min manat)
0,2024,NaN,3425222.0,11696.0,1085.0,2099001.0,1213002.0,959319.0,253683.0,100438.0,0.0,0.0
1,2023,NaN,2672397.0,9274.0,3923.0,1473613.0,1102104.0,870662.0,231442.0,83483.0,0.0,0.0
2,2022,NaN,2239187.0,4827.0,6179.0,1261872.0,905559.0,681886.0,223673.0,60750.0,0.0,0.0
3,2021,NaN,1298349.0,1837.0,2996.0,635110.0,632252.0,474553.0,157699.0,26154.0,0.0,0.0
4,2020,NaN,912765.0,4248.0,1128.0,343383.0,542383.0,408815.0,133568.0,21623.0,0.0,0.0

In [54]:
df1 = loadf(1)  # reload doesn't affect

df1.set_index(df1['Year'], inplace=True)
df1.drop(columns=['Year', 'Unnamed: 1', 'Tramvay (min manat)', 'Trolleybus (min manat)'], inplace=True)
en2azcols = {
    "Cəmi (min manat)": "Total Revenue per 1000 ₼",
    "Dəmir yolu (min manat)": "Railway per 1000 ₼",
    "Dəniz (min manat)": "Sea per 1000 ₼",
    "Hava (min manat)": "Air per 1000 ₼",
    "Avtomobil (min manat)": "Automobile per 1000 ₼",
    "Avtobus (min manat)": "Bus per 1000 ₼",
    "Taksi (min manat)": "Taxi per 1000 ₼",
    "Metro (min manat)": "Metro per 1000 ₼"
}
df1.rename(columns=en2azcols, inplace=True)
df1.index = pd.to_datetime(df1.index, format='%Y')
df1.sort_index(ascending=True, inplace=True)

df1.head()

,Total Revenue per 1000 ₼,Railway per 1000 ₼,Sea per 1000 ₼,Air per 1000 ₼,Automobile per 1000 ₼,Bus per 1000 ₼,Taxi per 1000 ₼,Metro per 1000 ₼
Year,,,,,,,,
1995-01-01,74114.0,1053.0,2809.0,48605.0,19063.0,17065.0,1998.0,2120.0
1996-01-01,84765.0,1140.0,1150.0,57119.0,21830.0,17034.0,4796.0,3058.0
1997-01-01,114437.0,1602.0,1074.0,45501.0,61229.0,48965.0,12264.0,4437.0
1998-01-01,133338.0,4188.0,446.0,40639.0,82827.0,62869.0,19958.0,4666.0
1999-01-01,127668.0,3013.0,381.0,31094.0,88429.0,64567.0,23862.0,4475.0