This project is running on Python 3.12.12

In [7]:
!python --version

Python 3.12.12

Our datasets will be placed on the `./datasets` folder.

In [9]:
!rm -rf ./datasets  # delete prior dataset folder if available
!mkdir ./datasets  # create new dataset folder
!echo "datasets folder created, success!"

datasets folder created, success!

Let's download our datasets from [OpenData](https://opendata.az)

In [10]:
# Hava temp
!wget -q --show-progress https://admin.opendata.az/dataset/3caada43-b48e-42ae-b166-d920490c2662/resource/8071a458-853b-4e1f-86f0-9a80d20db552/download/az015.csv -O ./datasets/data1.csv
# Neqliyyat qazanc
!wget -q --show-progress https://admin.opendata.az/dataset/1cb0a662-8737-45c2-a3f8-c8fa21888a1a/resource/d51060b9-27cf-4dab-b2b2-4397b33371af/download/nqliyyat-sektorunda-srniin-danmasndan-ld-olunan-glir-min-manat-dt_bj_029.csv -O ./datasets/data2.csv

./datasets/data1.cs 100%[===================>]   2.80K  --.-KB/s    in 0s
./datasets/data2.cs 100%[===================>]   2.59K  --.-KB/s    in 0s

Checking if the datasets downloaded:

In [11]:
!ls ./datasets

data1.csv  data2.csv

If yes, we can start analyzing our datasets!

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
!echo "Libraries loaded on the $(date)"

Libraries loaded on the Sun Jan 11 01:07:08 AM UTC 2026

In [15]:
df1 = pd.read_csv('./datasets/data1.csv', sep=";")
df2 = pd.read_csv('./datasets/data2.csv', sep=',')

In [16]:
df1.head()

,Unnamed: 0,2002,2003,2004,2005,2006,2007,2008,2009,2010,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1961-1990-ci illər üzrə orta çoxillik temperatur,NaN,NaN,NaN,NaN,"12,3",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Orta illik temperatur,"12,3","12,2","13,8","13,2","13,2","12,9","13,0","13,1","14,4",...,"13,4","13,6","13,0","13,5","15,0","14,4","13,8","16,2","14,3","14,7"
3,Orta illik temperaturun orta çoxillikdən fərqi,"0,0","-0,1","1,5","0,9","0,9","0,6","0,7","0,8","2,1",...,"1,1","1,3","0,7","1,2","2,7","2,1","1,5","3,9","2,0","2,4"
4,Ən yüksək (max) orta aylıq temperatur,"26,2","24,7","25,4","24,9","26,9","25,5","25,4","24,5","26,2",...,"28,5","24,7","24,7","26,6","28,4","25,4","25,4","25,8","25,2","24,8"

In [17]:
df2.head()

,Year,Unnamed: 1,Cəmi (min manat),Dəmir yolu (min manat),Dəniz (min manat),Hava (min manat),Avtomobil (min manat),Avtobus (min manat),Taksi (min manat),Metro (min manat),Tramvay (min manat),Trolleybus (min manat)
0,2024,NaN,3425222.0,11696.0,1085.0,2099001.0,1213002.0,959319.0,253683.0,100438.0,0.0,0.0
1,2023,NaN,2672397.0,9274.0,3923.0,1473613.0,1102104.0,870662.0,231442.0,83483.0,0.0,0.0
2,2022,NaN,2239187.0,4827.0,6179.0,1261872.0,905559.0,681886.0,223673.0,60750.0,0.0,0.0
3,2021,NaN,1298349.0,1837.0,2996.0,635110.0,632252.0,474553.0,157699.0,26154.0,0.0,0.0
4,2020,NaN,912765.0,4248.0,1128.0,343383.0,542383.0,408815.0,133568.0,21623.0,0.0,0.0